language: r
sudo: false
dist: trusty
cache: packages
addons:
  - ghostscript
r: bioc-devel
r_github_packages:
  - jimhester/covr
before_install:
  - tlmgr install bera nowidow parnotes marginfix etoolbox titlesec sectsty framed enumitem parskip soul placeins footmisc changepage xstring caption mathtools
after_success:
  - Rscript -e 'covr::codecov()'
